"""alter description to optional

Revision ID: ad9895ebc208
Revises: 53bcd7a319d8
Create Date: 2026-09-29 17:36:36.269301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad9895ebc208"
down_revision: Union[str, Sequence[str], None] = "53bcd7a319d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
